[workspace]
members = [
    "pahkat-types",
    # "pahkat-common",
    "pahkat-rpc",
    "pahkat-client-core",
    "pahkat-repomgr",
    "pahkat-cli",
]

exclude = [
    "pahkat-uploader",
]

[patch.crates-io]
libsqlite3-sys = { path = "../rusqlite/libsqlite3-sys" }
