=== What is Páhkat?

Páhkat is a tool to generate and manage a software repository, implementing the in-development standard
of the same name ("the Páhkat standard"), to solve the following problems:

* Platform-agnostic metadata format for defining packages, dependencies and related information
* Specific support for using the most platform-appropriate method for installing packages
* First-class support for localisation of relevant properties (such as name or description)
* Consistent linked data model
* An easy to parse format for computers and humans
* An OpenAPI-compliant HTTP API, easing development of Páhkat-compliant clients

This is the reference implementation of the in-development standard. There are several clients in development:

* https://github.com/divvun/pahkat-client-windows[Páhkat C#/WPF client] - Windows 8.1+
* https://github.com/divvun/pahkat-client-macos[Páhkat Swift/Cocoa client] - macOS 10.10+
* https://github.com/divvun/pahkat-client-core[Páhkat core library and command line client] - Windows 8.1+, Linux, macOS, etc

Páhkat is alpha software licensed under the Apache 2 license. This software should not be used in production.

=== Supported platforms

Páhkat can be compiled and run on any platform supported by the Rust compiler. A Páhkat repository is to be delivered via HTTPS,
and can be hosted on any platform that supports it.

The Páhkat repository itself is platform-agnostic. The platform field in a package is simply a string with a version guard.

Páhkat clients are responsible for implementation of support for the relevant platform identifiers.

Currently, the Páhkat C#/WPF supports Windows 8.1+ installers (both .msi and .exe), the macOS client supports .pkg files,
while the command-line client supports a prefix on any platform where the client can be run for a 
yet-to-be-documented XZ-compressed tarball format, as well as the platform-specific installers.