name: pahkat-service (Windows)

on: push

env:
  RUST_VERSION: stable
  CARGO_INCREMENTAL: 0
  RUSTUP_MAX_RETRIES: 10
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: full

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Divvun CI
      uses: divvun/actions/setup@master
      with:
        key: ${{ secrets.DIVVUN_KEY }}
    - name: Get version
      id: version
      uses: divvun/actions/version@master
      with:
        cargo: pahkat-rpc/Cargo.toml
        stable-channel: beta
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install build dependencies
      uses: divvun/actions/pahkat/init@master
      with:
        repo: https://pahkat.uit.no/devtools/
        channel: nightly
        packages: pahkat-uploader
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt
        target: i686-pc-windows-msvc
    - name: Set self-update channel to nightly
      id: self_update_channel
      if: ${{ steps.version.outputs.channel == 'nightly' }}
      run: |
        echo "::set-output name=channel::nightly"
    - name: Build Pahkat RPC DLL 
      run: |
        cd pahkat-rpc
        cargo build --lib --features windows --release --target i686-pc-windows-msvc
        cd ..
      env:
        RUSTC_BOOTSTRAP: 1
        CHANNEL: ${{ steps.self_update_channel.outputs.channel }}
    - name: Build Pahkat RPC Server
      run: |
        cd pahkat-rpc
        cargo build --bin winsvc --features windows --release --target i686-pc-windows-msvc
        cd ..
      env:
        RUSTC_BOOTSTRAP: 1
        CHANNEL: ${{ steps.self_update_channel.outputs.channel }}
    - name: Build Pahkat RPC Client
      run: |
        cd pahkat-rpc
        cargo build --bin client --features windows --release --target i686-pc-windows-msvc
        cd ..
      env:
        RUSTC_BOOTSTRAP: 1
        CHANNEL: ${{ steps.self_update_channel.outputs.channel }}
    - name: Create dist
      run: |
        mkdir dist
        mv target/i686-pc-windows-msvc/release/winsvc.exe dist/pahkat-service.exe
        mv target/i686-pc-windows-msvc/release/client.exe dist/pahkatc.exe
        mkdir -p dist-lib/bin
        mv target/i686-pc-windows-msvc/release/pahkat_rpc.dll dist-lib/bin/pahkat_rpc.dll
    - name: Sign code (server)
      uses: divvun/actions/codesign@master
      with:
        path: dist/pahkat-service.exe
    - name: Sign code (client)
      uses: divvun/actions/codesign@master
      with:
        path: dist/pahkatc.exe
    - name: Create installer
      id: installer
      uses: divvun/actions/inno-setup@master
      with:
        path: pahkat-rpc/resources/install.iss
        defines: Version=${{ steps.version.outputs.version }}
    - name: Bundle DLL
      id: lib_bundle
      uses: divvun/actions/create-txz@master
      with:
        path: dist-lib
    - name: Deploy (library)
      uses: divvun/actions/deploy@master
      with:
        package-id: libpahkat_rpc
        platform: windows
        arch: i686
        type: TarballPackage
        version: ${{ steps.version.outputs.version }}
        payload-path: ${{ steps.lib_bundle.outputs['txz-path'] }}
        repo: https://pahkat.thetc.se/devtools/
        channel: ${{ steps.version.outputs.channel }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy (installer)
      uses: divvun/actions/deploy@master
      with:
        package-id: pahkat-service
        platform: windows
        version: ${{ steps.version.outputs.version }}
        payload-path: ${{ steps.installer.outputs['installer-path'] }}
        repo: https://pahkat.thetc.se/divvun-installer/
        channel: ${{ steps.version.outputs.channel }}
        windows-kind: inno
        windows-product-code: "{6B3A048B-BB81-4865-86CA-61A0DF038CFE}_is1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
